---
apiVersion: v1
kind: Pod
metadata:
  name: bbc
  labels:
    app: bbc
spec:
  containers:
    - name: bbccontainer
      image: harikrishnanknr/gameover-web:v1
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: bbcnews
spec:
  selector:
    app: bbc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
