---
apiVersion: v1
kind: Pod
metadata:
  name: apple-ip 
  labels:
    app: apple-pod
spec: 
  containers:
  - name: applecontainer
    image: dockerharikrishnan/bbcnews
    ports:
    - name: apple-ip 
      containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: apple-ip 
  labels:
    app: apple-pod
spec: 
  containers:
  - name: appleservice
    image: dockerharikrishnan/bbcnews
    ports:
    - name: apple-ip 
      containerPort: 80
    Service type: Load balancer
