---
apiVersion: v1
kind: Pod
metadata:
  name: game 
  labels:
    app: gamepod
spec: 
  containers:
  - name: gamecontainer
    image: harikrishnanknr/gameover-web:v1
    ports:
    - name: gameport 
      containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: game
  labels:
    app: gameservice
spec: 
  containers:
  - name: gameservice
    image: harikrishnanknr/gameover-web:v1
    ports:
    - name: gameport 
      containerPort: 80
    Service type: Load balancer
